export default [
  { name: "India", code: "in" },
  { name: "United States", code: "us" },
  { name: "China", code: "cn" },
  { name: "Japan", code: "jp" },
  { name: "Germany", code: "de" },
  { name: "France", code: "fr" },
  { name: "United Kingdom", code: "gb" },
  { name: "Brazil", code: "br" },
  { name: "Canada", code: "ca" },
  { name: "Australia", code: "au" },

  { name: "Russia", code: "ru" },
  { name: "South Korea", code: "kr" },
  { name: "Italy", code: "it" },
  { name: "Spain", code: "es" },
  { name: "Mexico", code: "mx" },
  { name: "Indonesia", code: "id" },
  { name: "Turkey", code: "tr" },
  { name: "Saudi Arabia", code: "sa" },
  { name: "Argentina", code: "ar" },
  { name: "South Africa", code: "za" },

  { name: "Pakistan", code: "pk" },
  { name: "Bangladesh", code: "bd" },
  { name: "Sri Lanka", code: "lk" },
  { name: "Nepal", code: "np" },
  { name: "Thailand", code: "th" },
  { name: "Vietnam", code: "vn" },
  { name: "Malaysia", code: "my" },
  { name: "Singapore", code: "sg" },
  { name: "Philippines", code: "ph" },
  { name: "New Zealand", code: "nz" },

  { name: "Egypt", code: "eg" },
  { name: "Nigeria", code: "ng" },
  { name: "Kenya", code: "ke" },
  { name: "Morocco", code: "ma" },
  { name: "Israel", code: "il" },
  { name: "Iran", code: "ir" },
  { name: "Iraq", code: "iq" },
  { name: "UAE", code: "ae" },
  { name: "Qatar", code: "qa" },
  { name: "Kuwait", code: "kw" },

  { name: "Netherlands", code: "nl" },
  { name: "Switzerland", code: "ch" },
  { name: "Sweden", code: "se" },
  { name: "Norway", code: "no" },
  { name: "Denmark", code: "dk" },
  { name: "Poland", code: "pl" },
  { name: "Portugal", code: "pt" },
  { name: "Greece", code: "gr" },
  { name: "Ukraine", code: "ua" },
  { name: "Colombia", code: "co" }
]