// 201 countries / territories — ISO 3166-1 alpha-2 codes
// flagcdn.com/w80/<code>.png  (used by FlagLoader)
export default [
  // ── Asia ──────────────────────────────────────────────────────────────
  { name: "India",              code: "in" },
  { name: "China",              code: "cn" },
  { name: "Japan",              code: "jp" },
  { name: "South Korea",        code: "kr" },
  { name: "Indonesia",          code: "id" },
  { name: "Pakistan",           code: "pk" },
  { name: "Bangladesh",         code: "bd" },
  { name: "Philippines",        code: "ph" },
  { name: "Vietnam",            code: "vn" },
  { name: "Thailand",           code: "th" },
  { name: "Myanmar",            code: "mm" },
  { name: "Malaysia",           code: "my" },
  { name: "Nepal",              code: "np" },
  { name: "Sri Lanka",          code: "lk" },
  { name: "Cambodia",           code: "kh" },
  { name: "Laos",               code: "la" },
  { name: "Mongolia",           code: "mn" },
  { name: "Singapore",          code: "sg" },
  { name: "Brunei",             code: "bn" },
  { name: "Timor-Leste",        code: "tl" },
  { name: "North Korea",        code: "kp" },
  { name: "Taiwan",             code: "tw" },
  { name: "Hong Kong",          code: "hk" },
  { name: "Macau",              code: "mo" },
  { name: "Bhutan",             code: "bt" },
  { name: "Maldives",           code: "mv" },

  // ── Middle East ───────────────────────────────────────────────────────
  { name: "Saudi Arabia",       code: "sa" },
  { name: "UAE",                code: "ae" },
  { name: "Iran",               code: "ir" },
  { name: "Iraq",               code: "iq" },
  { name: "Israel",             code: "il" },
  { name: "Turkey",             code: "tr" },
  { name: "Syria",              code: "sy" },
  { name: "Jordan",             code: "jo" },
  { name: "Lebanon",            code: "lb" },
  { name: "Qatar",              code: "qa" },
  { name: "Kuwait",             code: "kw" },
  { name: "Bahrain",            code: "bh" },
  { name: "Oman",               code: "om" },
  { name: "Yemen",              code: "ye" },
  { name: "Palestine",          code: "ps" },
  { name: "Afghanistan",        code: "af" },
  { name: "Cyprus",             code: "cy" },
  { name: "Armenia",            code: "am" },
  { name: "Azerbaijan",         code: "az" },
  { name: "Georgia",            code: "ge" },

  // ── Central Asia ──────────────────────────────────────────────────────
  { name: "Kazakhstan",         code: "kz" },
  { name: "Uzbekistan",         code: "uz" },
  { name: "Tajikistan",         code: "tj" },
  { name: "Turkmenistan",       code: "tm" },
  { name: "Kyrgyzstan",         code: "kg" },

  // ── Europe ────────────────────────────────────────────────────────────
  { name: "Germany",            code: "de" },
  { name: "France",             code: "fr" },
  { name: "United Kingdom",     code: "gb" },
  { name: "Italy",              code: "it" },
  { name: "Spain",              code: "es" },
  { name: "Netherlands",        code: "nl" },
  { name: "Switzerland",        code: "ch" },
  { name: "Sweden",             code: "se" },
  { name: "Norway",             code: "no" },
  { name: "Denmark",            code: "dk" },
  { name: "Finland",            code: "fi" },
  { name: "Poland",             code: "pl" },
  { name: "Belgium",            code: "be" },
  { name: "Austria",            code: "at" },
  { name: "Portugal",           code: "pt" },
  { name: "Greece",             code: "gr" },
  { name: "Czech Republic",     code: "cz" },
  { name: "Hungary",            code: "hu" },
  { name: "Romania",            code: "ro" },
  { name: "Ukraine",            code: "ua" },
  { name: "Russia",             code: "ru" },
  { name: "Belarus",            code: "by" },
  { name: "Bulgaria",           code: "bg" },
  { name: "Serbia",             code: "rs" },
  { name: "Croatia",            code: "hr" },
  { name: "Slovakia",           code: "sk" },
  { name: "Slovenia",           code: "si" },
  { name: "Lithuania",          code: "lt" },
  { name: "Latvia",             code: "lv" },
  { name: "Estonia",            code: "ee" },
  { name: "Ireland",            code: "ie" },
  { name: "Iceland",            code: "is" },
  { name: "Luxembourg",         code: "lu" },
  { name: "Malta",              code: "mt" },
  { name: "Albania",            code: "al" },
  { name: "Bosnia-Herzegovina", code: "ba" },
  { name: "North Macedonia",    code: "mk" },
  { name: "Montenegro",         code: "me" },
  { name: "Kosovo",             code: "xk" },
  { name: "Moldova",            code: "md" },
  { name: "Monaco",             code: "mc" },
  { name: "Liechtenstein",      code: "li" },
  { name: "San Marino",         code: "sm" },
  { name: "Andorra",            code: "ad" },
  { name: "Vatican City",       code: "va" },

  // ── Africa ────────────────────────────────────────────────────────────
  { name: "Nigeria",            code: "ng" },
  { name: "Ethiopia",           code: "et" },
  { name: "Egypt",              code: "eg" },
  { name: "DR Congo",           code: "cd" },
  { name: "Tanzania",           code: "tz" },
  { name: "Kenya",              code: "ke" },
  { name: "Uganda",             code: "ug" },
  { name: "Algeria",            code: "dz" },
  { name: "Sudan",              code: "sd" },
  { name: "Morocco",            code: "ma" },
  { name: "Angola",             code: "ao" },
  { name: "Mozambique",         code: "mz" },
  { name: "Ghana",              code: "gh" },
  { name: "Madagascar",         code: "mg" },
  { name: "Cameroon",           code: "cm" },
  { name: "Ivory Coast",        code: "ci" },
  { name: "Niger",              code: "ne" },
  { name: "Burkina Faso",       code: "bf" },
  { name: "Mali",               code: "ml" },
  { name: "Malawi",             code: "mw" },
  { name: "Zambia",             code: "zm" },
  { name: "Senegal",            code: "sn" },
  { name: "Chad",               code: "td" },
  { name: "Somalia",            code: "so" },
  { name: "Zimbabwe",           code: "zw" },
  { name: "Guinea",             code: "gn" },
  { name: "Rwanda",             code: "rw" },
  { name: "Benin",              code: "bj" },
  { name: "Burundi",            code: "bi" },
  { name: "Tunisia",            code: "tn" },
  { name: "South Sudan",        code: "ss" },
  { name: "Togo",               code: "tg" },
  { name: "Sierra Leone",       code: "sl" },
  { name: "Libya",              code: "ly" },
  { name: "Congo",              code: "cg" },
  { name: "Liberia",            code: "lr" },
  { name: "Central African Rep",code: "cf" },
  { name: "Mauritania",         code: "mr" },
  { name: "Eritrea",            code: "er" },
  { name: "Namibia",            code: "na" },
  { name: "Gambia",             code: "gm" },
  { name: "Botswana",           code: "bw" },
  { name: "Gabon",              code: "ga" },
  { name: "Lesotho",            code: "ls" },
  { name: "Guinea-Bissau",      code: "gw" },
  { name: "Equatorial Guinea",  code: "gq" },
  { name: "Mauritius",          code: "mu" },
  { name: "Eswatini",           code: "sz" },
  { name: "Djibouti",           code: "dj" },
  { name: "Comoros",            code: "km" },
  { name: "Cabo Verde",         code: "cv" },
  { name: "Sao Tome & Principe",code: "st" },
  { name: "Seychelles",         code: "sc" },
  { name: "South Africa",       code: "za" },

  // ── Americas ──────────────────────────────────────────────────────────
  { name: "United States",      code: "us" },
  { name: "Canada",             code: "ca" },
  { name: "Mexico",             code: "mx" },
  { name: "Brazil",             code: "br" },
  { name: "Argentina",          code: "ar" },
  { name: "Colombia",           code: "co" },
  { name: "Chile",              code: "cl" },
  { name: "Peru",               code: "pe" },
  { name: "Venezuela",          code: "ve" },
  { name: "Ecuador",            code: "ec" },
  { name: "Bolivia",            code: "bo" },
  { name: "Paraguay",           code: "py" },
  { name: "Uruguay",            code: "uy" },
  { name: "Guyana",             code: "gy" },
  { name: "Suriname",           code: "sr" },
  { name: "Guatemala",          code: "gt" },
  { name: "Honduras",           code: "hn" },
  { name: "El Salvador",        code: "sv" },
  { name: "Nicaragua",          code: "ni" },
  { name: "Costa Rica",         code: "cr" },
  { name: "Panama",             code: "pa" },
  { name: "Belize",             code: "bz" },
  { name: "Cuba",               code: "cu" },
  { name: "Haiti",              code: "ht" },
  { name: "Dominican Republic", code: "do" },
  { name: "Jamaica",            code: "jm" },
  { name: "Trinidad & Tobago",  code: "tt" },
  { name: "Bahamas",            code: "bs" },
  { name: "Barbados",           code: "bb" },
  { name: "Saint Lucia",        code: "lc" },
  { name: "Grenada",            code: "gd" },
  { name: "Saint Vincent",      code: "vc" },
  { name: "Antigua & Barbuda",  code: "ag" },
  { name: "Dominica",           code: "dm" },
  { name: "Saint Kitts & Nevis",code: "kn" },

  // ── Oceania ───────────────────────────────────────────────────────────
  { name: "Australia",          code: "au" },
  { name: "New Zealand",        code: "nz" },
  { name: "Papua New Guinea",   code: "pg" },
  { name: "Fiji",               code: "fj" },
  { name: "Solomon Islands",    code: "sb" },
  { name: "Vanuatu",            code: "vu" },
  { name: "Samoa",              code: "ws" },
  { name: "Kiribati",           code: "ki" },
  { name: "Tonga",              code: "to" },
  { name: "Micronesia",         code: "fm" },
  { name: "Palau",              code: "pw" },
  { name: "Marshall Islands",   code: "mh" },
  { name: "Nauru",              code: "nr" },
  { name: "Tuvalu",             code: "tv" },
  { name: "Cook Islands",       code: "ck" },
  { name: "Niue",               code: "nu" },
];